'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")>  _
Partial Friend NotInheritable Class SavedCtls
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As SavedCtls = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New SavedCtls()),SavedCtls)
    
    Public Shared ReadOnly Property [Default]() As SavedCtls
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property xFrom() As Single
        Get
            Return CType(Me("xFrom"),Single)
        End Get
        Set
            Me("xFrom") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
    Public Property xTo() As Single
        Get
            Return CType(Me("xTo"),Single)
        End Get
        Set
            Me("xTo") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
    Public Property MajorColour() As Global.System.Drawing.Color
        Get
            Return CType(Me("MajorColour"),Global.System.Drawing.Color)
        End Get
        Set
            Me("MajorColour") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property yFrom() As Single
        Get
            Return CType(Me("yFrom"),Single)
        End Get
        Set
            Me("yFrom") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
    Public Property yTo() As Single
        Get
            Return CType(Me("yTo"),Single)
        End Get
        Set
            Me("yTo") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("wdLineStyleSingle")>  _
    Public Property MajorLineStyle() As Global.Microsoft.Office.Interop.Word.WdLineStyle
        Get
            Return CType(Me("MajorLineStyle"),Global.Microsoft.Office.Interop.Word.WdLineStyle)
        End Get
        Set
            Me("MajorLineStyle") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property PlotAsChart() As Boolean
        Get
            Return CType(Me("PlotAsChart"),Boolean)
        End Get
        Set
            Me("PlotAsChart") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property xNumEvery() As Single
        Get
            Return CType(Me("xNumEvery"),Single)
        End Get
        Set
            Me("xNumEvery") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property yNumEvery() As String
        Get
            Return CType(Me("yNumEvery"),String)
        End Get
        Set
            Me("yNumEvery") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property xDivs() As Single
        Get
            Return CType(Me("xDivs"),Single)
        End Get
        Set
            Me("xDivs") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property yDivs() As String
        Get
            Return CType(Me("yDivs"),String)
        End Get
        Set
            Me("yDivs") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Silver")>  _
    Public Property MinorColour() As Global.System.Drawing.Color
        Get
            Return CType(Me("MinorColour"),Global.System.Drawing.Color)
        End Get
        Set
            Me("MinorColour") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("wdLineStyleDashLargeGap")>  _
    Public Property MinorLineStyle() As Global.Microsoft.Office.Interop.Word.WdLineStyle
        Get
            Return CType(Me("MinorLineStyle"),Global.Microsoft.Office.Interop.Word.WdLineStyle)
        End Get
        Set
            Me("MinorLineStyle") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
    Public Property MajorWeight() As Single
        Get
            Return CType(Me("MajorWeight"),Single)
        End Get
        Set
            Me("MajorWeight") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
    Public Property MinorWeight() As Single
        Get
            Return CType(Me("MinorWeight"),Single)
        End Get
        Set
            Me("MinorWeight") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property PlotAsShapes() As Boolean
        Get
            Return CType(Me("PlotAsShapes"),Boolean)
        End Get
        Set
            Me("PlotAsShapes") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("PlotAsShapes")>  _
    Public Property PlotAs() As String
        Get
            Return CType(Me("PlotAs"),String)
        End Get
        Set
            Me("PlotAs") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("NumStandard")>  _
    Public Property Numbering() As String
        Get
            Return CType(Me("Numbering"),String)
        End Get
        Set
            Me("Numbering") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Ticks() As Boolean
        Get
            Return CType(Me("Ticks"),Boolean)
        End Get
        Set
            Me("Ticks") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Axes() As Boolean
        Get
            Return CType(Me("Axes"),Boolean)
        End Get
        Set
            Me("Axes") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property AxisLabels() As Boolean
        Get
            Return CType(Me("AxisLabels"),Boolean)
        End Get
        Set
            Me("AxisLabels") = value
        End Set
    End Property
End Class
