'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")>  _
Partial Friend NotInheritable Class SavedCtls
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As SavedCtls = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New SavedCtls()),SavedCtls)
    
    Public Shared ReadOnly Property [Default]() As SavedCtls
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property xFrom() As Single
        Get
            Return CType(Me("xFrom"),Single)
        End Get
        Set
            Me("xFrom") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
    Public Property xTo() As Single
        Get
            Return CType(Me("xTo"),Single)
        End Get
        Set
            Me("xTo") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
    Public Property majorColour() As Global.System.Drawing.Color
        Get
            Return CType(Me("majorColour"),Global.System.Drawing.Color)
        End Get
        Set
            Me("majorColour") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property yFrom() As Single
        Get
            Return CType(Me("yFrom"),Single)
        End Get
        Set
            Me("yFrom") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
    Public Property yTo() As Single
        Get
            Return CType(Me("yTo"),Single)
        End Get
        Set
            Me("yTo") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("wdLineStyleSingle")>  _
    Public Property MajorLineStyle() As Global.Microsoft.Office.Interop.Word.WdLineStyle
        Get
            Return CType(Me("MajorLineStyle"),Global.Microsoft.Office.Interop.Word.WdLineStyle)
        End Get
        Set
            Me("MajorLineStyle") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property PlotAs() As String
        Get
            Return CType(Me("PlotAs"),String)
        End Get
        Set
            Me("PlotAs") = value
        End Set
    End Property
End Class
